### ISSUE TITLE
Should include have access to upper scope?

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#14]
I'm trying to evaluate "package['dir']".
This works:

```
appname="www";                                                                  
APP = {                                                                         
dir = fmt "/opt/{appname}/";                                                  
};                                                                              
package = APP{};
```

This works as well:

```
appname="www";                                                                  
APP = {                                                                         
  inherit appname;                                                              
  dir = fmt "/opt/{appname}/";                                                  
};                                                                              
package = APP{};
```

But if I move APP to include, does not work:

```
appname="www";                                                                  
inc = include "inc.gcl";                                                        
package = inc.APP{};
```

error:

```
KeyError: 'appname'
# or if I put "inherit appname" in APP definition.
gcl.EvaluationError: Unbound variable: 'appname'
```

Also if I put content of APP in the included file and do:

```
appname="www";                                                                                                                  
package = include "inc.gcl";
```

Does not work as well.

If I do:

```
appname="www";                                                                  
inc = include "inc.gcl";                                                        
package = inc.APP{appname=appname};
```

I've got:

```
gcl.EvaluationError: <input>:4: while evaluating 'appname' in 'package = inc.APP{appname=appname};'
Reference cycle
```

**Comment by rix0rrr** [comment]
You didn't actually show me the contents of `inc.gcl`, but if they are:

```
# inc.gcl
APP = {                                                                         
    inherit appname;                                                              
    dir = fmt "/opt/{appname}/";                                                  
}; 
```

Then the behavior you're seeing is correct, and working as intended.

References in GCL are scoped to variables that are lexically "visible", and `appname` is not visible inside the include file (because you didn't define it). Instead, you should "declare" in your include file that you expect a parameter called `appname`, and then pass it in, like so:

```
# inc.gcl
appname;
APP = {
    dir = fmt "/opt/{appname}/";
};
```

Then use it as:

```
# main
appname = 'www';
inc = include 'inc.gcl' { inherit appname };

package = inc.APP;
```

Your other example, where you do 

```
appname = 'www';
package = inc.APP { appname = appname };
```

Indeed leads to a cycle because the appname to the right is referring to the appname on the left, which evaluates to the appname on the right, which is referring to the appname on the left, ... ad infinitum. This is _exactly_ what the `inherit` statement was made for (which will look for `appname` in outer scopes), like so:

```
appname = 'www';
package = inc.APP { inherit appname };
```

If you are going to use `appname` more in your include file, I would pick the first solution, otherwise I'd pick the second. Even in the second case, you'd need to declare you're expecting someone to pass in an `appname` variable inside the APP object, or you'd also get an 'undefined variable' error, like so:

```
# inc.gcl
APP = {
    appname;
    dir = fmt "/opt/{appname}/";
};
```

So you see the difference is only where you're expecting to set the `appname` variable.

A bit of this is explained in the section 'Scoping' in README.md, and a bit in 'You can always tell where a variable is coming from' in MOTIVATION.md.

**Comment by spinus** [comment]
Thank you very much for explaining that.
I was reading that part but looks like I was not careful enough. +1 for including those examples in the docs :-)

**Comment by spinus** [comment]
Awesome!
